/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import AdminProcess.AdminSystem;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alise
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    AdminSystem admin = new AdminSystem();

    public AdminFrame() {

        initComponents();
        jComboBoxSelection.setSelectedItem("None");
        jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSelection = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutputs = new javax.swing.JTextArea();
        jButtonSearch = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabelIDorName = new javax.swing.JLabel();
        jTextFieldIDorName = new javax.swing.JTextField();
        jButtonSearchOrDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ADMIN AREA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 50));

        jComboBoxSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<List All Player Games>", "<Search Player Games>", "<List Players Questions>", "<Delete Players>", "<List All Player Informations>", "<List Leaderboard>", "<Delete Submit Results>", "None" }));
        jComboBoxSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectionActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jTextAreaOutputs.setColumns(20);
        jTextAreaOutputs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutputs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 225, 176));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jButtonList.setText("List");
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonList, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabelIDorName.setText("ID,NAME");
        jPanel1.add(jLabelIDorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, 61, -1));
        jPanel1.add(jTextFieldIDorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        jButtonSearchOrDelete.setText("DeğişenButon");
        jButtonSearchOrDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchOrDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearchOrDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectionActionPerformed
        // TODO add your handling code here:
         String selected = jComboBoxSelection.getSelectedItem().toString();
        //burada sadece list butonu açılcak
        if (selected.equals("<List All Player Games>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(true); 
            jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);

          // burada playerların bilgileri var ıd name fakat parolo sanür atacaz
        } else if (selected.equals("<List All Player Informations>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(true);
             jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);

            //burada search butonu,name labeli,name textfieldı,search butonu açılcak if(searchPlayerGames==comboSelect)->adminSearch
        }else if (selected.equals("<Search Player Games>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(true);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(false);
            
            

            // burada Delete açılcak Id labeli Id textFieldı delete butonu olcak if(comboselected==delete )-> adminDelete
        } else if (selected.equals("<Delete Players>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(true);
            jLabelIDorName.setText("ID:");
            jLabelIDorName.setVisible(true);
            jButtonSearchOrDelete.setText("Delete");
            jButtonSearchOrDelete.setVisible(true);
            jTextFieldIDorName.setVisible(true);

        } else if (selected.equals("<List Players Questions>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(true);
            jButtonList.setVisible(true);
            jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);
            

        }else if (selected.equals("<Delete Submit Results>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(true);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(true);
            jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);
        }else if (selected.equals("<List Leaderboard>")) {
            jTextAreaOutputs.setText("");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(true);
             jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);

            //burada search butonu,name labeli,name textfieldı,search butonu açılcak if(searchPlayerGames==comboSelect)->adminSearch
        }else {
            jTextAreaOutputs.setText("");
            jComboBoxSelection.setSelectedItem("None");
            jButtonSearch.setVisible(false);
            jButtonDelete.setVisible(false);
            jButtonAdd.setVisible(false);
            jButtonList.setVisible(false);
            jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);
            // tüm butonalrı setvisiblefalse yap
        }


    }//GEN-LAST:event_jComboBoxSelectionActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
            jLabelIDorName.setText("Name:");
            jButtonSearchOrDelete.setText("Search");
            jLabelIDorName.setVisible(true);
            jButtonSearchOrDelete.setVisible(true);
            jTextFieldIDorName.setVisible(true);
           
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
      
        String selected = jComboBoxSelection.getSelectedItem().toString();
        
        if(selected.equals("<List All Player Informations>")) {
            String output="All Player Informations\n";
            output += AdminSystem.listofAllPlayersInformation("", 0);
        jTextAreaOutputs.setText(output);
        
       }
       else if(selected.equals("<List All Player Games>")){
        String output="Player Results\nNAME  SCORE  TIME\n";
       output+=AdminSystem.listOfAllPlayerGames("", 0);
            jTextAreaOutputs.setText(output);
       
       }
         else if(selected.equals("<List Players Questions>")){
             String output="Questions Of Players\n";
           output+=AdminSystem.listOfPlayerQuestions("", 0);
            jTextAreaOutputs.setText(output);
            
       
       }else if(selected.equals("<Delete Players>")){
            String output="All Player Informations\n";
            output+=AdminSystem.listofAllPlayersInformation("", 0);
            jTextAreaOutputs.setText(output);
       
       }else if(selected.equals("<Delete Submit Results>")){
            String output="NAME  SCORE  TIME\n";
           output+=AdminSystem.listOfAllPlayerGames("", 0);
            jTextAreaOutputs.setText(output);
            
       }else if(selected.equals("<List Leaderboard>")){
            String output="Leaderboards for this week\nNAME  SCORE  TIME\n";
       output+=AdminSystem.listLeaderBoard("", 0);
            jTextAreaOutputs.setText(output);
       
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try {
            // abi burayı şey yap ya bence adde basınca opton panel açılsın eminmisin diye orda ekelsin
            // şuan burda tek add şeklinde yapıoz
            AdminSystem.addUsersQuestion();
        } catch (IOException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSearchOrDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchOrDeleteActionPerformed
        String selected = jComboBoxSelection.getSelectedItem().toString();
        
        
        
        if (selected.equals("<Search Player Games>")) {
            String name = jTextFieldIDorName.getText();
             String output="Player Games\n"
                     + "Name  Score  Time\n";
         output+= AdminSystem.searchPlayerGames("", name, 0);
            jTextAreaOutputs.setText(output);
            jButtonSearchOrDelete.setVisible(false);
        jLabelIDorName.setVisible(false);
        jTextFieldIDorName.setVisible(false);
            
            
        }else if(selected.equals("<Delete Players>")){
            
            int Id = Integer.parseInt(jTextFieldIDorName.getText());
            String output="";
            boolean check = AdminSystem.deletePlayer(Id);
            
            if(check){
                output+="Player who has "+Id+" was deleted";
                jTextAreaOutputs.setText(output);
                
            }else{
                output+="Player who has "+Id+" was not deleted,because he/she does not exist";
                jTextAreaOutputs.setText(output);
                
            }
        
       }   else{
        jButtonSearchOrDelete.setVisible(false);
            jLabelIDorName.setVisible(false);
            jTextFieldIDorName.setVisible(false);}

    }//GEN-LAST:event_jButtonSearchOrDeleteActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            AdminSystem.deleteSubmitsResult();
            jTextAreaOutputs.setText("Deleted submit results");
            
        } catch (IOException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonList;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearchOrDelete;
    private javax.swing.JComboBox<String> jComboBoxSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIDorName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOutputs;
    private javax.swing.JTextField jTextFieldIDorName;
    // End of variables declaration//GEN-END:variables
}
