/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.*;
import javax.swing.*;
import Game.*;
import PlayerInformation.*;
import java.io.IOException;
import Main.Presantation1Console;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import userBehaviors.Estimating;
import userBehaviors.Taking;

public class cardPanel extends javax.swing.JPanel {

    protected RegisterAndSignIn registerAndSign = new RegisterAndSignIn();
    protected Player normalPlayer , adminPlayer;

    private JButton playButton;
    private JButton saveButton;

    /**
     * Creates new form cardPanell
     */
    public cardPanel() {

        initComponents();
    }

    public void showSignIn() {
        jTabbedPaneSıgnInAndRegister.setSelectedIndex(0);
    }

    public void showRegister() {
        jTabbedPaneSıgnInAndRegister.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSıgnInAndRegister = new javax.swing.JTabbedPane();
        jPanelSignIn = new javax.swing.JPanel();
        jLabelSignInNickname = new javax.swing.JLabel();
        jLabelSignInPassword = new javax.swing.JLabel();
        jTextFieldSignInNickname = new javax.swing.JTextField();
        jTextFieldSignInPassword = new javax.swing.JTextField();
        jButtonSignInPlay = new javax.swing.JButton();
        jButtonMainmenu = new javax.swing.JButton();
        jPanelRegister = new javax.swing.JPanel();
        jLabelRegisterNickname = new javax.swing.JLabel();
        jLabelRegisterPassword1 = new javax.swing.JLabel();
        jLabelRegisterPassword2 = new javax.swing.JLabel();
        jTextFieldRegisterNickname = new javax.swing.JTextField();
        jTextFieldRegisterPassword1 = new javax.swing.JTextField();
        jTextFieldPassword2 = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jButtonMainMenu = new javax.swing.JButton();

        jLabelSignInNickname.setText("Nickname:");

        jLabelSignInPassword.setText("Password:");

        jTextFieldSignInNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignInNicknameActionPerformed(evt);
            }
        });

        jTextFieldSignInPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSignInPasswordActionPerformed(evt);
            }
        });

        jButtonSignInPlay.setText("PLAY");
        jButtonSignInPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInPlayActionPerformed(evt);
            }
        });

        jButtonMainmenu.setText("EXIT");
        jButtonMainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignInLayout = new javax.swing.GroupLayout(jPanelSignIn);
        jPanelSignIn.setLayout(jPanelSignInLayout);
        jPanelSignInLayout.setHorizontalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignInLayout.createSequentialGroup()
                        .addComponent(jLabelSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSignInLayout.createSequentialGroup()
                        .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSignInLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButtonMainmenu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSignInPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldSignInPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanelSignInLayout.setVerticalGroup(
            jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignInLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSignInNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSignInPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jButtonMainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPaneSıgnInAndRegister.addTab("Sign-In", jPanelSignIn);

        jLabelRegisterNickname.setText("Nickname:");

        jLabelRegisterPassword1.setText("Password:");

        jLabelRegisterPassword2.setText("Password Again:");

        jTextFieldRegisterNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterNicknameActionPerformed(evt);
            }
        });

        jTextFieldRegisterPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterPassword1ActionPerformed(evt);
            }
        });

        jButtonRegister.setText("SAVE");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonMainMenu.setText("EXIT");
        jButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPassword2)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegisterNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegisterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPaneSıgnInAndRegister.addTab("Register", jPanelRegister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jTabbedPaneSıgnInAndRegister)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPaneSıgnInAndRegister)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSignInNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignInNicknameActionPerformed

    }//GEN-LAST:event_jTextFieldSignInNicknameActionPerformed

    private void jTextFieldSignInPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSignInPasswordActionPerformed
    }//GEN-LAST:event_jTextFieldSignInPasswordActionPerformed

    private void jTextFieldRegisterNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterNicknameActionPerformed

    private void jTextFieldRegisterPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterPassword1ActionPerformed

    private void jButtonSignInPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInPlayActionPerformed

        String nickname = jTextFieldSignInNickname.getText().trim(); // Sign-in nickname
        String password = jTextFieldSignInPassword.getText().trim(); // Sign-in password

        int result = -1;
        try {
            result = registerAndSign.signIn(nickname, password);
        } catch (IOException ex) {
            Logger.getLogger(cardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (result == 0) { // Admin
            adminPlayer=new Admin();
            
            new AdminFrame().setVisible(true);
            
            JOptionPane.showMessageDialog(this, "Admin mode opened!");
            
            

            SwingUtilities.getWindowAncestor(this).dispose();
        } else if (result == 1) {
            try {
                // Normal kullanıcı
                normalPlayer = new NormalPlayer(
                        nickname,
                        ReaderAndWriterFileProcess.getterLastIdFromFile(nickname),
                        new Taking(),
                        new Estimating()
                );
            } catch (IOException ex) {
            }
            
            JOptionPane.showMessageDialog(this, "Game Started!!");

            new GameFrame().setVisible(true);
            SwingUtilities.getWindowAncestor(this).dispose();
        } else { // Hatalı giriş
            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre hatalı!");
        }


    }//GEN-LAST:event_jButtonSignInPlayActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed

        String nickname = jTextFieldRegisterNickname.getText(); // Register nickname
        String password1 = jTextFieldRegisterPassword1.getText();
        String password2 = jTextFieldPassword2.getText();

        try {
            if (registerAndSign.register(nickname, password1, password2)) {

                JOptionPane.showMessageDialog(this, "Kayıt başarılı!");

                MainMenuFrame frame = (MainMenuFrame) SwingUtilities.getWindowAncestor(this);// bunu anlayamdım ali
               
               ;
                
        
        
        
                frame.showMenu(); // Menüye geri dön
            } else {
                JOptionPane.showMessageDialog(this, "Kayıt başarısız!");
            }
        } catch (IOException ex) {
            Logger.getLogger(cardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonMainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainmenuActionPerformed
        MainMenuFrame frame = (MainMenuFrame) SwingUtilities.getWindowAncestor(this);
        frame.showMenu();    }//GEN-LAST:event_jButtonMainmenuActionPerformed

    private void jButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMenuActionPerformed
        MainMenuFrame frame = (MainMenuFrame) SwingUtilities.getWindowAncestor(this);
        frame.showMenu();    }//GEN-LAST:event_jButtonMainMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMainMenu;
    private javax.swing.JButton jButtonMainmenu;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSignInPlay;
    private javax.swing.JLabel jLabelRegisterNickname;
    private javax.swing.JLabel jLabelRegisterPassword1;
    private javax.swing.JLabel jLabelRegisterPassword2;
    private javax.swing.JLabel jLabelSignInNickname;
    private javax.swing.JLabel jLabelSignInPassword;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPanel jPanelSignIn;
    private javax.swing.JTabbedPane jTabbedPaneSıgnInAndRegister;
    private javax.swing.JTextField jTextFieldPassword2;
    private javax.swing.JTextField jTextFieldRegisterNickname;
    private javax.swing.JTextField jTextFieldRegisterPassword1;
    private javax.swing.JTextField jTextFieldSignInNickname;
    private javax.swing.JTextField jTextFieldSignInPassword;
    // End of variables declaration//GEN-END:variables
}
