/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alise
 */
import GUI.*;
import Game.*;
import PlayerInformation.*;
import java.awt.HeadlessException;
import java.io.IOException;

public class SkorFrame extends javax.swing.JFrame {

    private Player player;

    public SkorFrame(Player player) throws IOException {
        initComponents();

        this.player = player;

        jLabelAnswer.setVisible(false);
        jLabelQuestion.setVisible(false);
        jTextFieldAnswer.setVisible(false);
        jTextFieldQuestion.setVisible(false);

        jLabelScore.setText(player.toString());

        Submit sb = new Submit(player);
        sb.writeOnScoreboard();// dosayya yazsın 
        String output = "Leaderboards for this week\n NAME    SCORE    TIME\n";
        output += sb.writeOnLeaderboard();

        jTextAreaScores.setText(output);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaScores = new javax.swing.JTextArea();
        jButtonAddQuestion = new javax.swing.JButton();
        jLabelSuggestion = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jLabelAnswer = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelScore.setText("Your Score: ");
        jPanel1.add(jLabelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 57, 316, 64));

        jTextAreaScores.setColumns(20);
        jTextAreaScores.setRows(5);
        jScrollPane1.setViewportView(jTextAreaScores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 130));

        jButtonAddQuestion.setText("AddQuestion");
        jButtonAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 189, 195, 53));

        jLabelSuggestion.setText("If you want,you can add question");
        jPanel1.add(jLabelSuggestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 166, -1, -1));

        jLabelQuestion.setText("Question:");
        jPanel1.add(jLabelQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));

        jTextFieldQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 260, -1));

        jLabelAnswer.setText("Answer:");
        jPanel1.add(jLabelAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, -1));
        jPanel1.add(jTextFieldAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddQuestionActionPerformed
        //bunu DİĞER BUTONA  AddQuestionFromUser.addQuestion("Burayı ali şey yapcak soru gelcek buraya", "aliş", player.getId());
        jLabelAnswer.setVisible(true);
        jLabelQuestion.setVisible(true);
        jTextFieldAnswer.setVisible(true);
        jTextFieldQuestion.setVisible(true);

        String question = jTextFieldQuestion.getText();
        String answer = jTextFieldAnswer.getText();

        AddQuestionFromUser.addQuestion(question, answer, player.getId());
        //soru eklendi ilave edilecek yer varmıdır bilmiyorum !!!!!!

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddQuestionActionPerformed

    private void jTextFieldQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuestionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddQuestion;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelSuggestion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaScores;
    private javax.swing.JTextField jTextFieldAnswer;
    private javax.swing.JTextField jTextFieldQuestion;
    // End of variables declaration//GEN-END:variables
}
